routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('/admin');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin','AdminController@index')->middleware("auth");
/*
Route::get('/admin/users','UserController@index')->middleware("auth");
Route::get('/admin/users/add','UserController@create')->name("users.create")->middleware("auth");
Route::post('/admin/users/store','UserController@store')->name("users.store")->middleware("auth");

Route::get('/admin/roles','RoleController@index')->middleware("auth");
*/

Route::resource('users','UserController');
Route::resource('course','CourseController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function roles(){
      return $this->belongsToMany("App\Role");
    }

    public function courses(){
      return $this->hasMany("App\Course");
    }

    public function rolesIds(){
      $id=[];
      foreach($this->roles as $role){
        $id[]=$role->id;
      }
      return $id;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\User;
use App\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        return view("admin.users.index",["users"=>User::paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //


          $data=[];

          $data['roles']=Role::all();
          return view("admin.users.create",$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $user = new User();
        $user->password = Hash::make($request->password);
        $user->email = $request->email;
        $user->name = $request->name;
        $user->save();
        $user->roles()->sync($request->roles);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $data=[];
        $data['user'] =  User::find($id);
        $data['roles']=Role::all();

        return view("admin.users.create",$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
      $user=User::find($id);
      $user->name=$request->name;
      $user->email=$request->email;
      if($request->password!=null)
      $user->password=$request->password;

      $user->save();
      $user->roles()->sync($request->roles);

      return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::find($id);
        $user->roles()->sync([]);
        $user->delete();
      return back()->with('message','Student Deleted Successfull !');
    }
}

resources/views/admin/users/add.blade.php
@extends('layouts.coreui')



@section('title','Admin Home')

@section("content")

<!-- http://localhost:8000/admin/users -->
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col">
      <div class="card">
<div class="card-header">
<strong>Horizontal</strong> Form</div>
<div class="card-body">
<form class="form-horizontal" action="" method="post">
<div class="form-group row">
 <label class="col-md-3 col-form-label" for="hf-email">Email</label>
<div class="col-md-9">
<input class="form-control" id="hf-email" type="email" name="hf-email" placeholder="Enter Email.." autocomplete="email">
<span class="help-block">Please enter your email</span>
</div>
</div>
<div class="form-group row">
<label class="col-md-3 col-form-label" for="hf-password">Password</label>
<div class="col-md-9">
<input class="form-control" id="hf-password" type="password" name="hf-password" placeholder="Enter Password.." autocomplete="current-password">
<span class="help-block">Please enter your password</span>
</div>
</div>
</form>
</div>
<div class="card-footer">
<button class="btn btn-sm btn-primary" type="submit">
<i class="fa fa-dot-circle-o"></i> Submit</button>
<button class="btn btn-sm btn-danger" type="reset">
<i class="fa fa-ban"></i> Reset</button>
</div>
</div>

    </div>

  </div>
</div>

@endsection

resources/views/admin/users/create.blade.php
@extends('layouts.coreui')



@section('title','Admin Home')

@section("content")

<!-- http://localhost:8000/admin/users -->
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col">
      <div class="card">
<div class="card-header">
<strong>Horizontal</strong> Form</div>
<div class="card-body">
<form class="form-horizontal" action="{{isset($user)?route('users.update',$user->id):route('users.store')}}" method="post">
  @csrf
  @if(isset($user))
    @method("put")
  @else
    @method("post")
  @endif
  <div class="form-group row">
     <label class="col-md-3 col-form-label" for="hf-email">Email</label>
      <div class="col-md-9">
          <input class="form-control" value="{{isset($user)? $user->name:''}}" id="hf-name" type="text" name="name" placeholder="Enter Name.." autocomplete="email">
          <span class="help-block">Please enter your name</span>
      </div>
  </div>
      <div class="form-group row">
         <label class="col-md-3 col-form-label" for="hf-email">Email</label>
          <div class="col-md-9">
              <input class="form-control" value="{{isset($user)? $user->email:''}}" id="hf-email" type="email" name="email" placeholder="Enter Email.." autocomplete="email">
              <span class="help-block">Please enter your email</span>
          </div>
      </div>
<div class="form-group row">
<label class="col-md-3 col-form-label" for="hf-password">Password</label>
<div class="col-md-9">
<input class="form-control" id="hf-password" type="password" name="password" placeholder="Enter Password.." autocomplete="current-password">
<span class="help-block">Please enter your password</span>
</div>
</div>


@foreach($roles as $role)
<div class="form-check">
  <input class="form-check-input" name="roles[]" type="checkbox" value="{{$role->id}}" id="defaultCheck{{$role->id}}" {{isset($user)?(in_array($role->id,$user->rolesIds())?'checked':''):''}} >
  <label class="form-check-label" for="defaultCheck{{$role->id}}">
    {{$role->role}}
  </label>
</div>
@endforeach


</div>
<div class="card-footer">
<button class="btn btn-sm btn-primary" type="submit">
<i class="fa fa-dot-circle-o"></i> Submit</button>
<button class="btn btn-sm btn-danger" type="reset">
<i class="fa fa-ban"></i> Reset</button>
</div>
</form>
</div>

    </div>

  </div>
</div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.coreui')



@section('title','Admin Home')

@section("content")

<!-- http://localhost:8000/admin/users -->
<div class="container-fluid mt-5">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <i class="fa fa-align-justify"></i> User Management
        </div>

        <div class="card-body">
          <a class="btn btn-success float-right mb-2" href="{{route('users.create')}}">Add User</a>
          <table class="table table-responsive-sm">

            <thead>
                <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Actions</th>
                </tr>
            </thead>

            <tbody>
              @foreach($users as $user)
                <tr>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>
                @foreach ($user->roles as $role)
                  <span class="badge badge-pill badge-info">{{$role->role}}<span>
                @endforeach
              </td>
                <td>
                  <form method="post" action="{{route('users.destroy',$user->id)}}">
                    @csrf
                    @method("delete")
                  <span class="badge badge-info"><a href="{{route('users.edit',$user->id)}}"><i class="icofont-edit-alt" style="color:#f0f3f"></i></a></span>


                  <span class="badge badge-danger"><button type="submit"  onclick="return confirm('Are You Sure? Want to Delete It.');" ><i class="icofont-ui-delete"></i></button></span>
                </form>
                </td>
                </tr>
               @endforeach
              </tbody>
          </table>

            {{$users}}

        </div>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/admin/users/role.blade.php
@extends('layouts.coreui')



@section('title','Admin Home')

@section("content")


@foreach($roles as $role)
  {{$role->id}}
  {{$role->role}}


@endforeach


<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <i class="fa fa-align-justify"></i> Simple Table
        </div>

        <div class="card-body">
          <table class="table table-responsive-sm">

            <thead>
                <tr>
                <th>Username</th>
                <th>Date registered</th>
                <th>Role</th>
                <th>Status</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                <td>Samppa Nori</td>
                <td>2012/01/01</td>
                <td>Member</td>
                <td>
                <span class="badge badge-success">Active</span>
                </td>
                </tr>
              </tbody>
          </table>


          <ul class="pagination">
          <li class="page-item">
          <a class="page-link" href="#">Prev</a>
          </li>
          <li class="page-item active">
          <a class="page-link" href="#">1</a>
          </li>
          <li class="page-item">
          <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
          <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
          <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
          <a class="page-link" href="#">Next</a>
          </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

@endsection